### PR TITLE
Testing crawl

### PR DESCRIPTION
**Pull request by gowtham1035**
Initially it was raising errors and it was cleared the by adding the functions test_crawl_external_link which helped in removing the errors.
Thursday 7

### CODE REVIEW

**Review by LaxmiNarayanaMurthyVemuri — APPROVED** [review]
@gowtham1035 Good job on the testcases. 

I need the code coverage result for the function.

**Comment by LaxmiNarayanaMurthyVemuri** [comment]
Please provide the output of the code coverage in form of a screenshot to validate the testcases coverage.

**Comment by gowtham1035** [comment]
I am sorry for not including the coverage snippet of the program.
coverage HTML

**Comment by gowtham1035** [comment]
Coverage

**Review by LaxmiNarayanaMurthyVemuri — APPROVED** [review]

**Pull request merged**
